from . import preprocessing,rules,trees
from .concepts import RandomQuestions,TrueOrFalse
from .clustering import Clustering,ClusteringEvaluationQuestions
from .clustering_generic import ClusteringGeneric
from .correlation import CorrelationMatrixJuego
from .discretization import Discretization
from .info_gain import InformationGain
from .normalization import Normalization
from .numerization import Numerization
from .oner import OneRQuestion
from .rule_metrics import RuleMetrics
from .perceptron import Perceptron
from .quantiles import Quantiles
from .boxplot import Boxplot
from .naivebayes import ApplyNaiveBayes
