name: Publish Python Package

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating release
      id-token: write  # Required for trusted publishing
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: setup
        uses: ./.github/actions/setup 
      - run: uv build
      - name: Publish package
        run: uv publish --verbose
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}

      # Optional: Create a GitHub release
      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}